using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Collections.Generic;

namespace ComponentIdGenerator
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var solutionDir = GetSolutionDirectory();
                if (solutionDir == null)
                {
                    Console.Error.WriteLine("Error: Could not find the solution directory (Server.sln).");
                    Environment.Exit(1);
                }

                var sharedAssemblyPath = Path.Combine(solutionDir, "Shared", "bin", "Debug", "netstandard2.1", "Shared.dll");
                // Add server bin dir only for dependency resolution (do NOT scan server types)
                var serverBinDir = Path.Combine(solutionDir, "Server", "bin", "Debug", "net8.0");
                var outputPath = Path.Combine(solutionDir, "Shared", "Replication", "ComponentTypeRegistry.Generated.cs");

                if (!File.Exists(sharedAssemblyPath))
                {
                    Console.Error.WriteLine(
                        $"Error: Shared assembly not found at '{sharedAssemblyPath}'. Please build the 'Shared' project first.");
                    Environment.Exit(1);
                }

                // Resolve dependencies from Shared and Server bin folders
                using var resolver = new AssemblyResolver(
                    Path.GetDirectoryName(sharedAssemblyPath) ?? string.Empty,
                    Directory.Exists(serverBinDir) ? serverBinDir : string.Empty
                );

                var sharedAssembly = Assembly.LoadFrom(sharedAssemblyPath);

                // Resolve IComponent type at runtime to avoid compile-time dependency
                var iComponentType = sharedAssembly.GetType("Shared.ECS.IComponent", throwOnError: true)!;

                // Base concrete component types (non-generic, non-abstract)
                var concreteComponents = SafeGetTypes(sharedAssembly)
                    .Where(t => t != null && iComponentType.IsAssignableFrom(t)
                                          && !t!.IsInterface
                                          && !t.IsAbstract
                                          && !t.IsGenericTypeDefinition)
                    .Cast<Type>()
                    .ToList();

                // Open generic component type definitions that implement IComponent
                var openGenericComponents = SafeGetTypes(sharedAssembly)
                    .Where(t => t != null && t.IsGenericTypeDefinition
                                          && iComponentType.IsAssignableFrom(t))
                    .Cast<Type>()
                    .ToList();

                // Build final list: all concrete components + constructed generic components
                var allComponents = new List<Type>();
                allComponents.AddRange(concreteComponents);

                foreach (var genericDef in openGenericComponents)
                {
                    var typeParams = genericDef.GetGenericArguments();
                    if (typeParams.Length != 1)
                    {
                        // For now, only support single-parameter generic components
                        continue;
                    }

                    foreach (var arg in concreteComponents)
                    {
                        try
                        {
                            var constructed = genericDef.MakeGenericType(arg);
                            if (iComponentType.IsAssignableFrom(constructed))
                            {
                                allComponents.Add(constructed);
                            }
                        }
                        catch
                        {
                            // Skip invalid constructions (constraint violations, etc.)
                        }
                    }
                }

                // De-duplicate and order deterministically
                var uniqueComponents = allComponents
                    .Distinct()
                    .OrderBy(t => t.FullName)
                    .ToList();

                var builder = new StringBuilder();
                builder.AppendLine("// <auto-generated/>");
                builder.AppendLine("// This file is automatically generated by the ComponentIdGenerator tool.");
                builder.AppendLine("// Do not modify this file manually.");
                builder.AppendLine();
                builder.AppendLine("using System;");
                builder.AppendLine();
                builder.AppendLine("namespace Shared.ECS.Replication");
                builder.AppendLine("{");
                builder.AppendLine("    public partial class ComponentTypeRegistry");
                builder.AppendLine("    { ");
                builder.AppendLine("        partial void InitializeMapping()");
                builder.AppendLine("        {");

                ushort id = 0;
                foreach (var type in uniqueComponents)
                {
                    var csharpTypeName = GetCSharpTypeName(type);
                    builder.AppendLine($"            _idToType.Add({id}, typeof({csharpTypeName}));");
                    builder.AppendLine($"            _typeToId.Add(typeof({csharpTypeName}), {id});");
                    id++;
                }

                builder.AppendLine("        }");
                builder.AppendLine("    }");
                builder.AppendLine("}");

                File.WriteAllText(outputPath, builder.ToString());

                Console.WriteLine(
                    $"Successfully generated component type registry with {uniqueComponents.Count} components from the Shared assembly.");
                Console.WriteLine($"Output file: {outputPath}");
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"An error occurred: {ex.Message}");
                Console.Error.WriteLine(ex.StackTrace);
                Environment.Exit(1);
            }
        }

        static IEnumerable<Type?> SafeGetTypes(Assembly assembly)
        {
            try
            {
                return assembly.GetTypes();
            }
            catch (ReflectionTypeLoadException ex)
            {
                return ex.Types;
            }
        }

        static string GetCSharpTypeName(Type type)
        {
            if (!type.IsGenericType)
                return (type.FullName ?? type.Name).Replace('+', '.');

            var def = type.GetGenericTypeDefinition();
            var baseName = (def.FullName ?? def.Name);
            var tickIndex = baseName.IndexOf('`');
            if (tickIndex >= 0)
                baseName = baseName.Substring(0, tickIndex);
            baseName = baseName.Replace('+', '.');

            var args = type.GetGenericArguments().Select(GetCSharpTypeName);
            return baseName + "<" + string.Join(", ", args) + ">";
        }

        static string? GetSolutionDirectory()
        {
            var dir = new DirectoryInfo(Environment.CurrentDirectory);
            while (dir != null && !dir.GetFiles("Server.sln").Any())
            {
                dir = dir.Parent;
            }

            return dir?.FullName;
        }

        private sealed class AssemblyResolver : IDisposable
        {
            private readonly string[] _lookupPaths;

            public AssemblyResolver(params string[] lookupPaths)
            {
                _lookupPaths = lookupPaths.Where(p => !string.IsNullOrEmpty(p)).ToArray();
                AppDomain.CurrentDomain.AssemblyResolve += OnAssemblyResolve;
            }

            private Assembly? OnAssemblyResolve(object? sender, ResolveEventArgs args)
            {
                foreach (var path in _lookupPaths)
                {
                    var assemblyPath = Path.Combine(path, new AssemblyName(args.Name).Name + ".dll");
                    if (File.Exists(assemblyPath))
                    {
                        try
                        {
                            return Assembly.LoadFrom(assemblyPath);
                        }
                        catch
                        {
                        }
                    }
                }

                return null;
            }

            public void Dispose()
            {
                AppDomain.CurrentDomain.AssemblyResolve -= OnAssemblyResolve;
            }
        }
    }
}