// <auto-generated/>
// This file is automatically generated by the ComponentIdGenerator tool.
// Do not modify this file manually.

using System;

namespace Shared.Replication
{
    public partial class ComponentTypeRegistry
    { 
        partial void InitializeMapping()
        {
            _idToType.Add(0, typeof(Shared.Damage.DamageApplyingComponent));
            _typeToId.Add(typeof(Shared.Damage.DamageApplyingComponent), 0);
            _idToType.Add(1, typeof(Shared.Damage.HealthComponent));
            _typeToId.Add(typeof(Shared.Damage.HealthComponent), 1);
            _idToType.Add(2, typeof(Shared.Damage.InvulnerableComponent));
            _typeToId.Add(typeof(Shared.Damage.InvulnerableComponent), 2);
            _idToType.Add(3, typeof(Shared.ECS.Components.BotTagComponent));
            _typeToId.Add(typeof(Shared.ECS.Components.BotTagComponent), 3);
            _idToType.Add(4, typeof(Shared.ECS.Components.ColorComponent));
            _typeToId.Add(typeof(Shared.ECS.Components.ColorComponent), 4);
            _idToType.Add(5, typeof(Shared.ECS.Components.LocalEntityTagComponent));
            _typeToId.Add(typeof(Shared.ECS.Components.LocalEntityTagComponent), 5);
            _idToType.Add(6, typeof(Shared.ECS.Components.NameComponent));
            _typeToId.Add(typeof(Shared.ECS.Components.NameComponent), 6);
            _idToType.Add(7, typeof(Shared.ECS.Components.PeerComponent));
            _typeToId.Add(typeof(Shared.ECS.Components.PeerComponent), 7);
            _idToType.Add(8, typeof(Shared.ECS.Components.PlayerTagComponent));
            _typeToId.Add(typeof(Shared.ECS.Components.PlayerTagComponent), 8);
            _idToType.Add(9, typeof(Shared.ECS.Components.PrefabComponent));
            _typeToId.Add(typeof(Shared.ECS.Components.PrefabComponent), 9);
            _idToType.Add(10, typeof(Shared.ECS.Components.ProjectileTagComponent));
            _typeToId.Add(typeof(Shared.ECS.Components.ProjectileTagComponent), 10);
            _idToType.Add(11, typeof(Shared.ECS.Components.SelfDestroyingComponent));
            _typeToId.Add(typeof(Shared.ECS.Components.SelfDestroyingComponent), 11);
            _idToType.Add(12, typeof(Shared.ECS.Components.SpawnAuthorityComponent));
            _typeToId.Add(typeof(Shared.ECS.Components.SpawnAuthorityComponent), 12);
            _idToType.Add(13, typeof(Shared.ECS.TickSync.ServerTickComponent));
            _typeToId.Add(typeof(Shared.ECS.TickSync.ServerTickComponent), 13);
            _idToType.Add(14, typeof(Shared.Physics.CollidingTagComponent));
            _typeToId.Add(typeof(Shared.Physics.CollidingTagComponent), 14);
            _idToType.Add(15, typeof(Shared.Physics.DoesNotOccupySpaceTagComponent));
            _typeToId.Add(typeof(Shared.Physics.DoesNotOccupySpaceTagComponent), 15);
            _idToType.Add(16, typeof(Shared.Physics.LocalBoundsComponent));
            _typeToId.Add(typeof(Shared.Physics.LocalBoundsComponent), 16);
            _idToType.Add(17, typeof(Shared.Physics.PositionComponent));
            _typeToId.Add(typeof(Shared.Physics.PositionComponent), 17);
            _idToType.Add(18, typeof(Shared.Physics.RotationComponent));
            _typeToId.Add(typeof(Shared.Physics.RotationComponent), 18);
            _idToType.Add(19, typeof(Shared.Physics.VelocityComponent));
            _typeToId.Add(typeof(Shared.Physics.VelocityComponent), 19);
            _idToType.Add(20, typeof(Shared.Physics.WorldAABBComponent));
            _typeToId.Add(typeof(Shared.Physics.WorldAABBComponent), 20);
            _idToType.Add(21, typeof(Shared.Prediction.PredictedComponent<Shared.Damage.DamageApplyingComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.Damage.DamageApplyingComponent>), 21);
            _idToType.Add(22, typeof(Shared.Prediction.PredictedComponent<Shared.Damage.HealthComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.Damage.HealthComponent>), 22);
            _idToType.Add(23, typeof(Shared.Prediction.PredictedComponent<Shared.Damage.InvulnerableComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.Damage.InvulnerableComponent>), 23);
            _idToType.Add(24, typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.BotTagComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.BotTagComponent>), 24);
            _idToType.Add(25, typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.ColorComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.ColorComponent>), 25);
            _idToType.Add(26, typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.LocalEntityTagComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.LocalEntityTagComponent>), 26);
            _idToType.Add(27, typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.NameComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.NameComponent>), 27);
            _idToType.Add(28, typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.PeerComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.PeerComponent>), 28);
            _idToType.Add(29, typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.PlayerTagComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.PlayerTagComponent>), 29);
            _idToType.Add(30, typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.PrefabComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.PrefabComponent>), 30);
            _idToType.Add(31, typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.ProjectileTagComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.ProjectileTagComponent>), 31);
            _idToType.Add(32, typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.SelfDestroyingComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.SelfDestroyingComponent>), 32);
            _idToType.Add(33, typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.SpawnAuthorityComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.ECS.Components.SpawnAuthorityComponent>), 33);
            _idToType.Add(34, typeof(Shared.Prediction.PredictedComponent<Shared.ECS.TickSync.ServerTickComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.ECS.TickSync.ServerTickComponent>), 34);
            _idToType.Add(35, typeof(Shared.Prediction.PredictedComponent<Shared.Physics.CollidingTagComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.Physics.CollidingTagComponent>), 35);
            _idToType.Add(36, typeof(Shared.Prediction.PredictedComponent<Shared.Physics.DoesNotOccupySpaceTagComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.Physics.DoesNotOccupySpaceTagComponent>), 36);
            _idToType.Add(37, typeof(Shared.Prediction.PredictedComponent<Shared.Physics.LocalBoundsComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.Physics.LocalBoundsComponent>), 37);
            _idToType.Add(38, typeof(Shared.Prediction.PredictedComponent<Shared.Physics.PositionComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.Physics.PositionComponent>), 38);
            _idToType.Add(39, typeof(Shared.Prediction.PredictedComponent<Shared.Physics.RotationComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.Physics.RotationComponent>), 39);
            _idToType.Add(40, typeof(Shared.Prediction.PredictedComponent<Shared.Physics.VelocityComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.Physics.VelocityComponent>), 40);
            _idToType.Add(41, typeof(Shared.Prediction.PredictedComponent<Shared.Physics.WorldAABBComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.Physics.WorldAABBComponent>), 41);
            _idToType.Add(42, typeof(Shared.Prediction.PredictedComponent<Shared.Respawn.RespawnComponent>));
            _typeToId.Add(typeof(Shared.Prediction.PredictedComponent<Shared.Respawn.RespawnComponent>), 42);
            _idToType.Add(43, typeof(Shared.Respawn.RespawnComponent));
            _typeToId.Add(typeof(Shared.Respawn.RespawnComponent), 43);
        }
    }
}
