name: Fly Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/fly-pr-review-apps@v1
        with:
          fly_api_token: ${{ secrets.FLY_API_TOKEN }}
          config_path: deploy/fly.toml
